[package]
name = "git-co"
version = "0.1.2"
edition = "2021"
license-file = "LICENSE"
description = "A command-line tool for simplified git branch checkout."
homepage = "https://github.com/ot07/git-co"
repository = "https://github.com/ot07/git-co"
readme = "README.md"
keywords = ["git", "branch", "checkout", "cli"]

[dependencies]
clap = { version = "4.3.0", features = ["derive"] }
git2 = "0.17.1"
skim = "0.10.4"
tuikit = "0.5.0"
